### ISSUE TITLE
chef-client 11.x fails to converge 

### ISSUE THREAD

**Issue by sclark007** [chef-cookbooks/yum-centos#15]
looks like the converge fails for all chef client version 11.x 

       NoMethodError
       -------------
       undefined method `[]' for nil:NilClass
       
       Cookbook Trace:
       ---------------
         /tmp/kitchen/cache/cookbooks/yum-centos/recipes/default.rb:27:in `block in from_file'
         /tmp/kitchen/cache/cookbooks/yum-centos/recipes/default.rb:26:in `each'
         /tmp/kitchen/cache/cookbooks/yum-centos/recipes/default.rb:26:in `from_file'
       
       Relevant File Content:
       ----------------------
       /tmp/kitchen/cache/cookbooks/yum-centos/recipes/default.rb:
       
        20:  
        21:  node.default['yum-centos']['repos'] << value_for_platform(centos: {
        22:                                           '>= 7.0' => 'cr',
        23:                                           '< 7.0' => 'contrib'
        24:                                       })
        25:  
        26:  node['yum-centos']['repos'].each do |repo|
        27>>   if node['yum'][repo]['managed']
        28:      yum_repository repo do
        29:        baseurl node['yum'][repo]['baseurl']
        30:        cost node['yum'][repo]['cost']
        31:        description node['yum'][repo]['description']
        32:        enabled node['yum'][repo]['enabled']
        33:        enablegroups node['yum'][repo]['enablegroups']
        34:        exclude node['yum'][repo]['exclude']
        35:        failovermethod node['yum'][repo]['failovermethod']
        36:        fastestmirror_enabled node['yum'][repo]['fastestmirror_enabled']
       
       
       Running handlers:
       [2015-07-09T17:48:07+00:00] ERROR: Running exception handlers
       Running handlers complete
       [2015-07-09T17:48:07+00:00] ERROR: Exception handlers complete
       [2015-07-09T17:48:07+00:00] FATAL: Stacktrace dumped to /tmp/kitchen/cache/chef-stacktrace.out
       Chef Client failed. 0 resources updated in 6.687364766 seconds
       [2015-07-09T17:48:07+00:00] ERROR: undefined method `[]' for nil:NilClass
       [2015-07-09T17:48:07+00:00] FATAL: Chef::Exceptions::ChildConvergeError: Chef run process exited unsuccessfully (exit code 1)

**Comment by Diffusive** [comment]
We've also got this issue but it does not appear to be due to the chef-client version. We receive the exact same error but it is due to the value_for_platform statment.

The attribute assumes that you are running this on centos since you are using yum-centos, however if it encounters another platform (run ohai | grep platform) then the statement will return nil and add nil to the end of the default['yum-centos']['repos'] hash.

Our problem came up because our platform evaluated to "redhat" so we fail.

I seem to be unable to make a pull request, but moving the default case out of the centos block like this works:

default['yum-centos']['repos'] = %w(base updates extras centosplus fasttrack) << (value_for_platform(centos: {
                                                                                                       '>= 7.0' => 'cr' },
                                                                                                       :default => 'contrib'
                                                                                                     ))

**Comment by qubitrenegade** [comment]
I ran into this issue when running tests.  We have a cookbook that includes yum, yum-centos, and yum-epel.  When including the yum-centos cookbook it causes tests to fail for the entire cookbook.

I wrote a stripped down version of our cookbook and tests here: https://github.com/qubitrenegade/yum_test

The default recipe is what we are running in our cookbook, then I have individual yum_test, yum-centos_test, and yum-epel_test which include each recipe individually, the corresponding tests are in spec/.

What I find interesting is that including yum, or yum-epel does not generate the error, however, when including yum-centos it causes all other 'include_recipe' cookbooks to fail.

```
  1) test_yum::default When all attributes are default, on an unspecified platform converges successfully
     Failure/Error: expect { chef_run }.to_not raise_error
       expected no Exception, got #<NoMethodError: undefined method `[]' for nil:NilClass> with backtrace:
         # /tmp/d20151027-14164-1ivx565/cookbooks/yum-centos/recipes/default.rb:22:in `block in from_file'
         # /tmp/d20151027-14164-1ivx565/cookbooks/yum-centos/recipes/default.rb:21:in `each'
         # /tmp/d20151027-14164-1ivx565/cookbooks/yum-centos/recipes/default.rb:21:in `from_file'
         # /tmp/d20151027-14164-1ivx565/cookbooks/test_yum/recipes/default.rb:8:in `block in from_file'
         # /tmp/d20151027-14164-1ivx565/cookbooks/test_yum/recipes/default.rb:7:in `each'
         # /tmp/d20151027-14164-1ivx565/cookbooks/test_yum/recipes/default.rb:7:in `from_file'
         # ./spec/unit/recipes/default_spec.rb:13:in `block (3 levels) in <top (required)>'
         # ./spec/unit/recipes/default_spec.rb:17:in `block (4 levels) in <top (required)>'
         # ./spec/unit/recipes/default_spec.rb:17:in `block (3 levels) in <top (required)>'
     # ./spec/unit/recipes/default_spec.rb:17:in `block (3 levels) in <top (required)>'

  2) test_yum::default When all attributes are default, on an unspecified platform includes recipe: yum
     Failure/Error: runner.converge(described_recipe)
     NoMethodError:
       undefined method `[]' for nil:NilClass
     # /tmp/d20151027-14164-185u2gc/cookbooks/yum-centos/recipes/default.rb:22:in `block in from_file'
     # /tmp/d20151027-14164-185u2gc/cookbooks/yum-centos/recipes/default.rb:21:in `each'
     # /tmp/d20151027-14164-185u2gc/cookbooks/yum-centos/recipes/default.rb:21:in `from_file'
     # /tmp/d20151027-14164-185u2gc/cookbooks/test_yum/recipes/default.rb:8:in `block in from_file'
     # /tmp/d20151027-14164-185u2gc/cookbooks/test_yum/recipes/default.rb:7:in `each'
     # /tmp/d20151027-14164-185u2gc/cookbooks/test_yum/recipes/default.rb:7:in `from_file'
     # ./spec/unit/recipes/default_spec.rb:13:in `block (3 levels) in <top (required)>'
     # ./spec/unit/recipes/default_spec.rb:22:in `block (4 levels) in <top (required)>'
```
